//! Simulation orchestrator managing blob states, physics stepping, and scalar field evaluation.

use super::field::{evaluate_field, evaluate_with_temperature, ScalarField};
use super::metaball::Blob;
use super::physics::{step_blob, PhysicsParams};

/// Minimal fast XorShift64 PRNG for deterministic noise without external dependencies.
#[derive(Debug, Clone)]
struct SimplePrng {
    state: u64,
}

impl SimplePrng {
    fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 {
                0x5465_726d_4c61_7661
            } else {
                seed
            },
        }
    }

    fn next_u32(&mut self) -> u32 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x as u32
    }

    /// Returns a float in $[-1.0, 1.0]$.
    fn next_f32_signed(&mut self) -> f32 {
        let val = (self.next_u32() & 0xFFFF) as f32 / 65535.0;
        val * 2.0 - 1.0
    }
}

/// The central LavaTerm simulation container.
#[derive(Debug, Clone)]
pub struct Simulation {
    /// Active metaballs.
    pub blobs: Vec<Blob>,
    /// Physics parameters.
    ///
    /// Derived state: `noise` and `buoyancy` are recomputed from `base_params`,
    /// the reactive multipliers, and the user offset on every
    /// [`apply_signals`](Self::apply_signals) /
    /// [`apply_audio_signals`](Self::apply_audio_signals) call. Writing them
    /// directly does not survive the next poll — use
    /// [`nudge_buoyancy`](Self::nudge_buoyancy) for user input. The remaining
    /// fields are never modulated and are safe to read.
    pub params: PhysicsParams,
    /// Scalar field evaluator.
    pub field: ScalarField,
    /// Total elapsed simulation time in seconds.
    pub elapsed_time: f32,
    /// Base radius scale for compact / adaptive viewports.
    pub radius_scale: f32,
    /// Physics parameters as configured by the user. Reactive modulation is computed
    /// relative to these so `[simulation]` values in `config.toml` are never discarded.
    base_params: PhysicsParams,
    /// Blob radii as generated by [`Simulation::new`], before any radius scaling.
    /// Radius modulation is relative to these, preserving per-blob random variety.
    base_radii: Vec<f32>,
    /// Accumulated user buoyancy offset from keyboard and scroll interactions.
    user_buoyancy_offset: f32,
    /// Buoyancy multiplier derived from the active reactive source (1.0 = no modulation).
    reactive_buoyancy_scale: f32,
    /// Noise multiplier derived from the active reactive source (1.0 = no modulation).
    reactive_noise_scale: f32,
    /// Radius multiplier derived from the active reactive source (1.0 = no modulation).
    radius_multiplier: f32,
    /// Internal deterministic PRNG.
    prng: SimplePrng,
}

impl Simulation {
    /// Maximum allowable delta time to avoid simulation instability.
    pub const MAX_DT: f32 = 0.10;

    /// Lowest buoyancy `Config::validate` accepts from `[simulation].buoyancy`.
    /// Clamping a freshly constructed simulation to this range would silently rewrite
    /// a valid configuration, so construction must not clamp at all.
    const MIN_CONFIG_BUOYANCY: f32 = 0.0;
    /// Highest buoyancy `Config::validate` accepts from `[simulation].buoyancy`.
    const MAX_CONFIG_BUOYANCY: f32 = 5.0;

    /// Creates a new simulation with `blob_count` blobs arranged with initial thermal distribution.
    pub fn new(params: PhysicsParams, blob_count: usize, seed: u64) -> Self {
        let mut prng = SimplePrng::new(seed);
        let mut blobs = Vec::with_capacity(blob_count);

        let count = blob_count.max(1);
        for i in 0..count {
            let frac = (i as f32 + 0.5) / count as f32;
            let x = 0.15 + 0.70 * frac;
            // Half start near bottom, half start near top with alternating temperatures
            let is_bottom = i % 2 == 0;
            let y = if is_bottom {
                0.10 + 0.10 * prng.next_f32_signed()
            } else {
                0.85 + 0.10 * prng.next_f32_signed()
            };
            let temp = if is_bottom { 0.90 } else { 0.10 };
            let radius = 0.08 + 0.04 * (prng.next_f32_signed().abs());

            let mut blob = Blob::new(x, y, radius, temp);
            blob.vx = prng.next_f32_signed() * 0.05;
            blob.vy = prng.next_f32_signed() * 0.05;
            blobs.push(blob);
        }

        let base_radii = blobs.iter().map(|b| b.radius).collect();
        let mut sim = Self {
            blobs,
            base_params: params,
            params,
            field: ScalarField,
            elapsed_time: 0.0,
            radius_scale: 1.0,
            base_radii,
            user_buoyancy_offset: 0.0,
            reactive_buoyancy_scale: 1.0,
            reactive_noise_scale: 1.0,
            radius_multiplier: 1.0,
            prng,
        };
        sim.sync_derived_params();
        sim
    }

    /// Returns the user-configured physics parameters, before reactive modulation.
    pub fn base_params(&self) -> PhysicsParams {
        self.base_params
    }

    /// Recomputes `self.params` from `base_params`, the reactive multipliers, and the
    /// accumulated user buoyancy offset. Idempotent: calling it repeatedly never
    /// compounds, so keyboard input survives signal polling.
    ///
    /// The result is *not* clamped. A valid `[simulation].buoyancy` of `5.0` must stay
    /// `5.0`; clamping here would silently rewrite configuration that `Config::validate`
    /// already accepted. Runaway is prevented instead by bounding the user offset in
    /// [`Self::nudge_buoyancy`].
    fn sync_derived_params(&mut self) {
        self.params.noise = self.base_params.noise * self.reactive_noise_scale;
        self.params.buoyancy =
            self.base_params.buoyancy * self.reactive_buoyancy_scale + self.user_buoyancy_offset;
    }

    /// Applies a user-requested buoyancy change (keyboard speed control, scroll pressure).
    ///
    /// The change is stored as an offset on top of the configured base value, so reactive
    /// modulation can no longer silently discard it.
    ///
    /// The offset is bounded to the range that can still change the result. Without that,
    /// holding a speed key would bank credit that later `SlowDown` presses must first
    /// exhaust, making the control feel unresponsive in both directions.
    pub fn nudge_buoyancy(&mut self, delta: f32) {
        // Only the headroom relative to the current reactive value can change the
        // result, so the offset is bounded by exactly that. This keeps a held speed key
        // from banking credit that later SlowDown presses must first exhaust, without
        // constraining the configured baseline itself.
        let signal_term = self.base_params.buoyancy * self.reactive_buoyancy_scale;
        let max_offset = Self::MAX_CONFIG_BUOYANCY - signal_term;
        let min_offset = Self::MIN_CONFIG_BUOYANCY - signal_term;

        self.user_buoyancy_offset =
            (self.user_buoyancy_offset + delta).clamp(min_offset.min(0.0), max_offset.max(0.0));
        self.sync_derived_params();
    }

    /// Replaces the configured physics baseline, discarding any accumulated user offset.
    ///
    /// Used by [`crate::widget::CompactScaler::adapt_simulation`] so that compact
    /// physics scaling becomes the new baseline instead of being overwritten by the next
    /// reactive poll.
    pub fn set_base_params(&mut self, params: PhysicsParams) {
        self.base_params = params;
        self.user_buoyancy_offset = 0.0;
        self.sync_derived_params();
    }

    /// Sets the reactive radius multiplier and recomputes blob radii.
    fn set_radius_multiplier(&mut self, radius_multiplier: f32) {
        self.radius_multiplier = radius_multiplier;
        self.sync_derived_radii();
    }

    /// Recomputes every blob radius from `base_radii`, `radius_scale`, and the reactive
    /// `radius_multiplier`. Idempotent, and preserves the per-blob variety generated by
    /// [`Simulation::new`].
    fn sync_derived_radii(&mut self) {
        debug_assert_eq!(
            self.blobs.len(),
            self.base_radii.len(),
            "blobs and base_radii must stay the same length; blobs is pub so external \
             code must not add or remove metaballs after Simulation::new"
        );
        for (blob, &base) in self.blobs.iter_mut().zip(self.base_radii.iter()) {
            blob.radius = (base * self.radius_scale * self.radius_multiplier).max(0.01);
        }
    }

    /// Scales all blob radii by `scale` and sets `self.radius_scale`.
    ///
    /// Idempotent: radii are recomputed from their generated base values rather than
    /// multiplied in place, so repeated calls with the same scale do not compound.
    pub fn apply_radius_scale(&mut self, scale: f32) {
        self.radius_scale = scale;
        self.sync_derived_radii();
    }

    /// Advances the simulation by $\Delta t$ seconds.
    pub fn step(&mut self, dt: f32) {
        let dt_effective = dt.clamp(0.0, Self::MAX_DT);
        self.elapsed_time += dt_effective;

        for blob in &mut self.blobs {
            let noise_x = self.prng.next_f32_signed();
            let noise_y = self.prng.next_f32_signed();
            step_blob(blob, &self.params, dt_effective, (noise_x, noise_y));
        }
    }

    /// Evaluates the scalar field at coordinate `(px, py)` in $[0.0, 1.0] \times [0.0, 1.0]$.
    #[inline]
    pub fn evaluate_field(&self, px: f32, py: f32) -> f32 {
        evaluate_field(&self.blobs, px, py)
    }

    /// Evaluates field intensity and temperature at `(px, py)`.
    #[inline]
    pub fn evaluate_at(&self, px: f32, py: f32) -> (f32, f32) {
        evaluate_with_temperature(&self.blobs, px, py)
    }

    /// Dynamically modulates physics constants and blob parameters from normalized reactive signals.
    ///
    /// Modulation is applied as a multiplier on the user-configured `base_params`, so
    /// `[simulation]` values from `config.toml` remain the reference point and a setting
    /// of `noise = 0.0` is respected. Idempotent — safe to call every poll.
    pub fn apply_signals(&mut self, signals: &crate::reactive::SystemSignals) {
        // CPU load modulates Brownian thermal noise and turbulence (base * (1.0 + cpu * 2.5))
        self.reactive_noise_scale = 1.0 + signals.cpu_load * 2.5;

        // Battery level modulates convection: low battery -> sluggish lava, high -> lively.
        // Relative to the configured buoyancy so `[simulation].buoyancy` stays meaningful.
        self.reactive_buoyancy_scale = 0.625 + signals.battery_level * 0.75;

        // RAM memory usage modulates blob size: higher memory -> larger, expanding blobs.
        // Applied per-blob on top of each blob's own generated radius, preserving variety.
        self.set_radius_multiplier(0.85 + signals.memory_usage * 0.40);

        self.sync_derived_params();
    }

    /// Advances the simulation by $\Delta t$ seconds while applying reactive system signals.
    pub fn step_reactive(&mut self, dt: f32, signals: &crate::reactive::SystemSignals) {
        self.apply_signals(signals);
        self.step(dt);
    }

    /// Dynamically modulates physics constants and blob kinetics from normalized audio spectrum signals.
    ///
    /// Like [`Simulation::apply_signals`], modulation is a multiplier on the configured
    /// base values and is idempotent, so keyboard speed control survives audio polling.
    pub fn apply_audio_signals(&mut self, audio: &crate::audio::AudioSignals) {
        // Bass kick gives strong convective thrust and upward buoyancy surge
        self.reactive_buoyancy_scale = 1.0 + audio.bass * 1.875;

        // Midrange frequencies modulate fluid turbulence and Brownian noise
        self.reactive_noise_scale = 1.0 + audio.mid * 2.5;

        // Audio does not modulate radius. Reset it so that radii fall back to the
        // configured base rather than retaining a system-signal multiplier.
        self.set_radius_multiplier(1.0);

        self.sync_derived_params();

        // Treble adds subtle kinetic energy jitter
        if audio.treble > 0.3 {
            for blob in &mut self.blobs {
                blob.vx += (self.prng.next_f32_signed()) * audio.treble * 0.02;
            }
        }
    }

    /// Advances the simulation by $\Delta t$ seconds while applying reactive audio signals.
    pub fn step_audio(&mut self, dt: f32, audio: &crate::audio::AudioSignals) {
        self.apply_audio_signals(audio);
        self.step(dt);
    }

    /// Applies a user interaction impulse to the simulation.
    pub fn apply_interaction(&mut self, interaction: &super::interaction::Interaction) {
        match *interaction {
            super::interaction::Interaction::Shockwave { x, y, force } => {
                super::interaction::apply_shockwave(&mut self.blobs, x, y, force);
            }
            super::interaction::Interaction::Stir {
                x,
                y,
                vx,
                vy,
                radius,
            } => {
                super::interaction::apply_stir(&mut self.blobs, x, y, vx, vy, radius);
            }
            super::interaction::Interaction::Ripple { intensity } => {
                let prng = &mut self.prng;
                super::interaction::apply_ripple(&mut self.blobs, intensity, || {
                    prng.next_f32_signed()
                });
            }
            super::interaction::Interaction::Pressure { delta } => {
                self.nudge_buoyancy(delta * 0.15);
            }
            super::interaction::Interaction::ThermalPulse {
                x,
                y,
                temperature_delta,
                radius,
            } => {
                super::interaction::apply_thermal_pulse(
                    &mut self.blobs,
                    x,
                    y,
                    temperature_delta,
                    radius,
                );
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audio::AudioSignals;
    use crate::core::interaction::Interaction;
    use crate::reactive::SystemSignals;

    #[test]
    fn test_simulation_apply_interaction() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        let center_blob_idx = 0;
        let blob_initial_y = sim.blobs[center_blob_idx].y;

        // Apply shockwave near blob
        sim.apply_interaction(&Interaction::Shockwave {
            x: sim.blobs[center_blob_idx].x,
            y: blob_initial_y - 0.1,
            force: 1.5,
        });

        assert!(
            sim.blobs[center_blob_idx].vy > 0.0,
            "Shockwave below blob must push blob upward"
        );

        // Apply pressure
        let prev_buoyancy = sim.params.buoyancy;
        sim.apply_interaction(&Interaction::Pressure { delta: 1.0 });
        assert!(sim.params.buoyancy > prev_buoyancy);
    }

    #[test]
    fn test_simulation_step_deterministic() {
        let mut sim1 = Simulation::new(PhysicsParams::default(), 6, 42);
        let mut sim2 = Simulation::new(PhysicsParams::default(), 6, 42);

        for _ in 0..10 {
            sim1.step(0.033);
            sim2.step(0.033);
        }

        assert_eq!(sim1.blobs.len(), sim2.blobs.len());
        for (b1, b2) in sim1.blobs.iter().zip(sim2.blobs.iter()) {
            assert!((b1.x - b2.x).abs() < 1e-6);
            assert!((b1.y - b2.y).abs() < 1e-6);
        }
    }

    #[test]
    fn test_simulation_bounds_dt() {
        let mut sim = Simulation::new(PhysicsParams::default(), 4, 123);
        sim.step(10.0); // Extreme pause
        assert!(sim.elapsed_time <= Simulation::MAX_DT + 1e-5);
    }

    #[test]
    fn test_simulation_reactive_signal_modulation() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        let low_signals = SystemSignals::new(0.0, 0.0, 0.0, 0.0);
        let high_signals = SystemSignals::new(1.0, 1.0, 1.0, 1.0);

        sim.apply_signals(&low_signals);
        let low_noise = sim.params.noise;
        let low_buoyancy = sim.params.buoyancy;
        let low_radius = sim.blobs[0].radius;

        sim.apply_signals(&high_signals);
        let high_noise = sim.params.noise;
        let high_buoyancy = sim.params.buoyancy;
        let high_radius = sim.blobs[0].radius;

        assert!(
            high_noise > low_noise,
            "CPU load must increase turbulence noise"
        );
        assert!(
            high_buoyancy > low_buoyancy,
            "Battery charge must increase buoyancy"
        );
        assert!(
            high_radius > low_radius,
            "Memory usage must increase blob size"
        );
    }

    #[test]
    fn test_simulation_audio_signal_modulation() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        let quiet = AudioSignals::new(0.0, 0.0, 0.0, 0.0);
        let drop = AudioSignals::new(1.0, 0.8, 0.6, 0.9);

        sim.apply_audio_signals(&quiet);
        let quiet_buoyancy = sim.params.buoyancy;
        let quiet_noise = sim.params.noise;

        sim.apply_audio_signals(&drop);
        let drop_buoyancy = sim.params.buoyancy;
        let drop_noise = sim.params.noise;

        assert!(
            drop_buoyancy > quiet_buoyancy,
            "Bass kick must increase buoyancy"
        );
        assert!(
            drop_noise > quiet_noise,
            "Midrange audio must increase turbulence noise"
        );
    }

    /// Regression for issue #84 Bug 1: `apply_signals` used to overwrite `blob.radius`
    /// with an `i % 3` formula, collapsing all blobs onto 3 repeating sizes.
    #[test]
    fn test_apply_signals_preserves_radius_variety() {
        fn distinct_radii(sim: &Simulation) -> usize {
            let mut seen = sim
                .blobs
                .iter()
                .map(|b| (b.radius * 1e6) as u32)
                .collect::<Vec<_>>();
            seen.sort_unstable();
            seen.dedup();
            seen.len()
        }

        let mut sim = Simulation::new(PhysicsParams::default(), 12, 1337);
        let before = distinct_radii(&sim);
        assert!(
            before > 3,
            "setup must generate more than 3 distinct radii, got {before}"
        );

        let hi = SystemSignals::new(1.0, 1.0, 1.0, 1.0);
        for _ in 0..5 {
            sim.apply_signals(&hi);
        }

        assert_eq!(
            distinct_radii(&sim),
            before,
            "polling signals must not collapse per-blob radius variety"
        );
    }

    /// Regression for issue #84 Bug 2: `apply_signals` used to hardcode `noise` and
    /// `buoyancy`, discarding whatever the user configured in `config.toml`.
    #[test]
    fn test_apply_signals_respects_configured_values() {
        let configured = PhysicsParams {
            gravity: 0.12,
            buoyancy: 2.0,
            viscosity: 0.93,
            noise: 0.0,
            thermal_transfer_rate: 0.40,
        };
        let mut sim = Simulation::new(configured, 6, 42);

        // Even saturated signals must not resurrect noise the user disabled.
        let saturated = SystemSignals::new(1.0, 1.0, 1.0, 1.0);
        sim.apply_signals(&saturated);

        assert_eq!(
            sim.params.noise, 0.0,
            "configured noise = 0.0 must stay 0.0 under reactive modulation"
        );
        assert!(
            sim.params.buoyancy >= configured.buoyancy * 0.625,
            "reactive modulation must scale around configured buoyancy, got {}",
            sim.params.buoyancy
        );
    }

    /// Regression for issue #84 Bug 3: keyboard speed control was overwritten by the
    /// next signal poll, making SpeedUp/SlowDown dead keys in `--system`/`--audio` mode.
    #[test]
    fn test_keyboard_buoyancy_survives_signal_poll() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        for _ in 0..10 {
            sim.nudge_buoyancy(0.1);
        }
        let after_keys = sim.params.buoyancy;

        sim.apply_signals(&SystemSignals::new(0.0, 0.0, 0.5, 0.0));
        let after_poll = sim.params.buoyancy;

        assert_eq!(
            after_poll, after_keys,
            "signal polling must not discard the user's accumulated buoyancy offset"
        );

        // Repeated polls must stay stable, not compound or drift.
        sim.apply_signals(&SystemSignals::new(0.0, 0.0, 0.5, 0.0));
        assert_eq!(sim.params.buoyancy, after_keys);

        // And lowering must still work, bounded by the configured range.
        sim.nudge_buoyancy(-100.0);
        assert_eq!(sim.params.buoyancy, Simulation::MIN_CONFIG_BUOYANCY);
    }

    /// `apply_audio_signals` must respect configured values and preserve user offsets too.
    #[test]
    fn test_audio_signals_preserve_user_buoyancy_offset() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        sim.nudge_buoyancy(0.5);
        let after_keys = sim.params.buoyancy;

        sim.apply_audio_signals(&AudioSignals::new(1.0, 0.8, 0.6, 0.9));

        assert!(
            sim.params.buoyancy > after_keys,
            "bass surge should still raise buoyancy on top of the user offset"
        );
        let after_audio = sim.params.buoyancy;
        sim.apply_audio_signals(&AudioSignals::new(1.0, 0.8, 0.6, 0.9));
        assert_eq!(
            sim.params.buoyancy, after_audio,
            "audio polling must be idempotent"
        );
    }

    /// `apply_radius_scale` must be idempotent. It used to multiply radii in place, so
    /// repeated calls with the same scale compounded the result.
    #[test]
    fn test_apply_radius_scale_is_idempotent() {
        let mut sim = Simulation::new(PhysicsParams::default(), 8, 7);
        sim.apply_radius_scale(0.85);
        let once = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();
        sim.apply_radius_scale(0.85);
        let twice = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();
        assert_eq!(once, twice, "re-applying the same scale must not compound");
    }

    /// Regression for review finding P1: construction clamped `params.buoyancy` into
    /// the historical `apply_pressure` range, silently rewriting configuration values
    /// that `Config::validate` had already accepted.
    #[test]
    fn test_construction_preserves_valid_config_range() {
        for configured in [0.0_f32, 0.1, 0.8, 3.0, 5.0] {
            let sim = Simulation::new(
                PhysicsParams {
                    buoyancy: configured,
                    ..PhysicsParams::default()
                },
                6,
                42,
            );
            assert_eq!(
                sim.params.buoyancy, configured,
                "configured buoyancy {configured} must survive construction unchanged"
            );
        }
    }

    /// Regression for review finding P2: the offset used to keep accumulating after the
    /// effective value had saturated, so later `SlowDown` presses did nothing visible
    /// until the banked credit was spent.
    #[test]
    fn test_buoyancy_offset_does_not_bank_credit() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        sim.apply_signals(&SystemSignals::new(0.0, 0.0, 0.0, 0.0));

        for _ in 0..1_000 {
            sim.nudge_buoyancy(0.1);
        }
        let saturated = sim.params.buoyancy;
        assert_eq!(saturated, Simulation::MAX_CONFIG_BUOYANCY);

        // The very first SlowDown must have a visible effect.
        sim.nudge_buoyancy(-0.1);
        assert!(
            sim.params.buoyancy < saturated,
            "first SlowDown after saturation must be visible: {} vs {saturated}",
            sim.params.buoyancy
        );

        // And the offset must stay within the range that can still change the result.
        for _ in 0..1_000 {
            sim.nudge_buoyancy(0.1);
        }
        assert!(
            sim.params.buoyancy <= Simulation::MAX_CONFIG_BUOYANCY,
            "sustained SpeedUp must not push buoyancy past the configured maximum"
        );

        for _ in 0..1_000 {
            sim.nudge_buoyancy(-0.1);
        }
        assert_eq!(sim.params.buoyancy, Simulation::MIN_CONFIG_BUOYANCY);
    }

    /// Regression for review finding P3: `CompactScaler::adapt_simulation` wrote
    /// `sim.params` directly, so the next reactive poll rebuilt from the un-compacted
    /// baseline and silently dropped the compact physics scaling.
    #[test]
    fn test_set_base_params_makes_compact_scaling_durable() {
        let profile = crate::widget::CompactProfile {
            blob_count: 6,
            radius_scale: 0.85,
            buoyancy_scale: 1.25,
            noise_scale: 0.90,
        };
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        crate::widget::CompactScaler::adapt_simulation(&profile, &mut sim);

        assert_eq!(sim.base_params().buoyancy, 0.80 * 1.25);
        assert_eq!(sim.base_params().noise, 0.15 * 0.90);

        // A reactive poll must scale around the compact baseline, not erase it.
        // battery = 1.0 -> buoyancy scale = 0.625 + 1.0 * 0.75 = 1.375
        // cpu    = 0.0 -> noise scale    = 1.0
        sim.apply_signals(&SystemSignals::new(0.0, 0.0, 1.0, 0.0));
        assert!(
            (sim.params.buoyancy - 0.80 * 1.25 * 1.375).abs() < 1e-4,
            "compact buoyancy baseline lost after poll: {}",
            sim.params.buoyancy
        );
        assert!(
            (sim.params.noise - 0.15 * 0.90).abs() < 1e-4,
            "compact noise baseline lost after poll: {}",
            sim.params.noise
        );

        // A user nudge must also preserve the compact baseline.
        sim.nudge_buoyancy(0.1);
        assert_eq!(sim.base_params().buoyancy, 0.80 * 1.25);
    }

    /// Audio does not drive radius, so it must clear any system-signal radius multiplier
    /// rather than leaving a stale one behind.
    #[test]
    fn test_audio_signals_reset_radius_multiplier() {
        let mut sim = Simulation::new(PhysicsParams::default(), 6, 42);
        let generated = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();

        sim.apply_signals(&SystemSignals::new(0.0, 1.0, 0.0, 0.0));
        let system_scaled = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();

        // Audio does not drive radius, so every blob must fall back to its own
        // generated radius rather than keeping the system multiplier.
        sim.apply_audio_signals(&AudioSignals::new(0.0, 0.0, 0.0, 0.0));
        let audio_scaled = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();

        for i in 0..sim.blobs.len() {
            let before = system_scaled[i];
            let after = audio_scaled[i];
            let base = generated[i];
            assert!(
                after < before,
                "blob {i} kept the system radius multiplier: {after} vs {before}"
            );
            assert!(
                (after - base).abs() < 1e-6,
                "blob {i} must return to its generated radius: {after} vs {base}"
            );
        }

        // and audio mode must be stable across repeated polls
        sim.apply_audio_signals(&AudioSignals::new(0.0, 0.0, 0.0, 0.0));
        let audio_again = sim.blobs.iter().map(|b| b.radius).collect::<Vec<_>>();
        assert_eq!(audio_scaled, audio_again);
    }

    /// `apply_radius_scale` must compose with reactive radius modulation, not reset it.
    #[test]
    fn test_radius_scale_composes_with_signal_modulation() {
        let mut sim = Simulation::new(PhysicsParams::default(), 8, 99);
        let generated: Vec<f32> = sim.blobs.iter().map(|b| b.radius).collect();

        // radius = generated * radius_scale * radius_multiplier
        // memory_usage = 1.0 -> multiplier = 0.85 + 0.40 = 1.25
        let radius_scale = 0.85;
        let radius_multiplier = 1.25;
        sim.apply_radius_scale(radius_scale);
        sim.apply_signals(&SystemSignals::new(0.0, 1.0, 0.0, 0.0));

        for (blob, &base) in sim.blobs.iter().zip(generated.iter()) {
            let expected = (base * radius_scale * radius_multiplier).max(0.01);
            assert!(
                (blob.radius - expected).abs() < 1e-6,
                "radius must be the product of both scales: {} vs expected {}",
                blob.radius,
                expected
            );
        }

        // Rescaling after a poll must be reflected, and must survive the next poll
        // rather than being reset from `generated`.
        sim.apply_radius_scale(0.5);
        let after_rescale = sim.blobs[0].radius;
        sim.apply_signals(&SystemSignals::new(0.0, 1.0, 0.0, 0.0));
        assert!(
            (sim.blobs[0].radius - after_rescale).abs() < 1e-6,
            "rescaled radius must survive the next poll: {} vs {}",
            sim.blobs[0].radius,
            after_rescale
        );
    }
}
